### ISSUE TITLE
语法错误问题

### ISSUE THREAD

**Issue by miwoy** [node-webot/co-wechat#18]
babel默认配置会把node_modules过滤，所以编译时node_modules里的es6语法并未转换
我查看了一下babel插件的源码，都是经过编译后再上传到npm上的，所以我希望你们也可以把编译结果文件传到npm上，而不要把源码直接上传，这样对小白使用起来不太方便

**Comment by JacksonTian** [comment]
使用 2.x

**Comment by JacksonTian** [comment]
如果你要用 2.x，请保证你的 Node 版本在 7.6 及以上。
