### ISSUE TITLE
请问co-wechat2.x版本只能运行在node7.x或更高版本?

### ISSUE THREAD

**Issue by zhangtaodeveloper** [node-webot/co-wechat#24]
问题由来:
  我们公司环境是node6.x使用框架是koa2,集成co-wechat2.1运行是提示语法有问题,查看了co-wechat2.1源码发现里面使用了node7.x + 才支持的await等,所以 想要使用co-wechat 2.x是不是只能升级node7.x+ ,我们不能调整koa至1因为框架很多有依赖,所以想问下 是不是如此?假如是  请 作者在页面标注下,防止其他用户出现类似问题,谢谢啦!

**Comment by JacksonTian** [comment]
是。请看 readme ：

![2017-08-09 6 45 03](https://user-images.githubusercontent.com/327019/29117995-eb83958a-7d32-11e7-9890-766899f045c0.png)
