### ISSUE TITLE
请问关于路由的问题

### ISSUE THREAD

**Issue by zhangtaodeveloper** [node-webot/co-wechat#25]
这样的形式是否部署后会占用项目根目录,假如想要支持多个目录,例如:
   1.  项目地址/wechat 被用来监听 wechat那边的通知和回调
   2.  项目地址/其他   被用来监听自己项目的通知和回调这样如何配置呢?

**Comment by zhangtaodeveloper** [comment]
不好意思 问题已解决.

**Comment by bestplay** [comment]
请问怎么解决的？

app.use(wechat(config).middleware(handler);

不能， app.use('/wechat',wechat(config).middleware(handler);

额，koa 新手。

我错过了什么

**Comment by JacksonTian** [comment]
Use koa-router with it.
