### ISSUE TITLE
2.1.0处理xml被提前处理的问题

### ISSUE THREAD

**Issue by ilaipi** [node-webot/co-wechat#27]
新增的处理xml提前处理的方法，可能需要加个判断body是不是字符串

我用的koa2+koa-bodyparser4.2.x，导致`ctx.request.body`是个`{}`，所以就一直报错了。。  

搞了一下午，刚刚突然发现是新增了那个判断。

**Comment by JacksonTian** [comment]
closed via 305f4db

**Comment by JacksonTian** [comment]
已经发布 2.1.1
