### ISSUE TITLE
如何在handle中获取ctx上下文,现在只传递了一个message

### ISSUE THREAD

**Issue by dcboy** [node-webot/co-wechat#30]

**Comment by dcboy** [comment]
// 业务逻辑处理
        const body = await handle(formatted);

这里handle 需要获取ctx

**Comment by zuoye520** [comment]
@dcboy  

我把源码稍微改动了一下，我是这么处理的。
const body = await handle(formatted, ctx); 
前面接收
async(message, ctx) => {
		return '测试消息';
	}

**Comment by dcboy** [comment]
router.all([path], async(ctx, next) => {
                                    return wechat('xxxx').middleware(controller[v].bind(null, ctx))(ctx, next);
                                });

这样也可以,不改代码了

**Comment by JacksonTian** [comment]
我加上 ctx 作为第二个参数吧。

**Comment by JacksonTian** [comment]
发布了 2.2.0
