### ISSUE TITLE
请问eggjs我想动态传入配置信息，如何传呢？【使用的是微信】

### ISSUE THREAD

**Issue by xinnian1992** [node-webot/co-wechat#31]
WechatController.prototype.autokey = wechat(config).middleware(async(message, ctx)=> {
        console.log(message);
    });
请指点迷津，谢谢诶

**Comment by xinnian1992** [comment]
因为我要提供服务给不同的公众号，可惜无法在里面写函数

**Comment by JacksonTian** [comment]
https://github.com/node-webot/co-wechat#相同路由支持多账号

**Comment by xinnian1992** [comment]
谢谢 @JacksonTian
