### ISSUE TITLE
co-wechat bug

### ISSUE THREAD

**Issue by lglie** [node-webot/co-wechat#7]
lib/wechat.js:
182行： var encrypted =! !(query.encrypt_type && query.encrypt_type === 'aes' && query.msg_signature);
应  为：var encrypted = !(query.encrypt_type && query.encrypt_type === 'aes' && query.msg_signature);
283行：if (!query.encrypt_type || query.encrypt_type === 'raw')
应  为：if (!!query.encrypt_type || query.encrypt_type === 'raw')
都是感叹号，一行多了，一行少了

还有当在app.js页面（主页面）使用的时候没问题，但在其它页面做中间件使用的时候，必须要跟上路由器的get和post方法，co-wechat才能起作用，这可能是一个bug。我用的是koa-router

**Comment by mukaiu** [comment]
感叹号是正确的~
