### ISSUE TITLE
建议签名异常的时候不要直接返回，而是交给业务逻辑处理

### ISSUE THREAD

**Issue by ninozhang** [node-webot/co-wechat#9]
当前逻辑是提示签名异常就直接返回错误信息了，然而有些情况是希望捕获这个异常并且自定义返回结果的。

**Comment by JacksonTian** [comment]
什么情况下会签名异常？

- 被中间攻击？
- ？？

**Comment by ninozhang** [comment]
- 项目不单单只响应微信的消息推送的时候
- 部署在阿里云上，负载均衡对部署的服务进行心跳检测的时候
- 。。。

**Comment by ninozhang** [comment]
调整了一下亲的代码，错误信息放到 this.error 里面，方便业务处理

`'use strict';

const getRawBody = require('raw-body');
const xml2js = require('xml2js');
const crypto = require('crypto');
const WXBizMsgCrypt = require('wechat-crypto');

// 模板被我放到另一个文件了
const tpl = require('./tpl');

function getSignature(timestamp, nonce, token) {
  let shasum = crypto.createHash('sha1');
  let arr = [token, timestamp, nonce].sort();
  shasum.update(arr.join(''));

  return shasum.digest('hex');
};

function parseXML(xml) {
  return function(done) {
    xml2js.parseString(xml, { trim: true }, done);
  };
};

/*!
 * 将内容回复给微信的封装方法
 */
function reply(content, fromUsername, toUsername) {
  let info = {};
  let type = 'text';
  info.content = content || '';
  if (Array.isArray(content)) {
    type = 'news';
  } else if (typeof content === 'object') {
    if (content.hasOwnProperty('type')) {
      if (content.type === 'customerService') {
        return reply2CustomerService(fromUsername, toUsername, content.kfAccount);
      }
      type = content.type;
      info.content = content.content;
    } else {
      type = 'music';
    }
  }
  info.msgType = type;
  info.createTime = new Date().getTime();
  info.toUsername = toUsername;
  info.fromUsername = fromUsername;
  return tpl.compiled(info);
};

function reply2CustomerService(fromUsername, toUsername, kfAccount) {
  let info = {};
  info.msgType = 'transfer_customer_service';
  info.createTime = new Date().getTime();
  info.toUsername = toUsername;
  info.fromUsername = fromUsername;
  info.content = {};
  if (typeof kfAccount === 'string') {
    info.content.kfAccount = kfAccount;
  }
  return tpl.compiled(info);
};

/**
 * 将xml2js解析出来的对象转换成直接可访问的对象
 */
function formatMessage(result) {
  let message = {};
  if (typeof result === 'object') {
    for (let key in result) {
      if (!(result[key] instanceof Array) || result[key].length === 0) {
        continue;
      }
      if (result[key].length === 1) {
        let val = result[key][0];
        if (typeof val === 'object') {
          message[key] = formatMessage(val);
        } else {
          message[key] = (val || '').trim();
        }
      } else {
        message[key] = [];
        result[key].forEach(function(item) {
          message[key].push(formatMessage(item));
        });
      }
    }
  }
  return message;
};

module.exports = (options) => {
  let token;
  let appid;
  let encodingAESKey;
  let cryptor;

  // 读取配置
  if (typeof options === 'string') {
    token = options;
  } else if (typeof options === 'object' && options.token) {
    token = options.token;
    appid = options.appid || '';
    encodingAESKey = options.encodingAESKey || '';
  } else {
    throw new Error('please check your config');
  }

  // 准备加密方法
  if (encodingAESKey) {
    cryptor = new WXBizMsgCrypt(token, encodingAESKey, appid);
  }

  return function*(next) {
    const query = this.query;
    // 加密模式
    const isEncrypted = !!(query.encrypt_type && query.encrypt_type === 'aes' && query.msg_signature);
    const timestamp = query.timestamp;
    const nonce = query.nonce;
    const echostr = query.echostr;
    const method = this.method;

    let isWeixin = false;
    let formated;

    // 处理 GET 请求
    if (method === 'GET') {
      let isValid = false;

      if (isEncrypted) {
        // 校验加密后的签名
        let signature = query.msg_signature;
        isValid = signature === cryptor.getSignature(timestamp, nonce, echostr);
      } else {
        // 校验签名
        isValid = query.signature === getSignature(timestamp, nonce, token);
      }

      // 签名校验出错，提示错误
      if (!isValid) {
        this.error = new Error('WeChat Invalid signature');
      } else {
        isWeixin = true;
      }

      // 处理 POST 请求
    } else if (method === 'POST') {
      if (!isEncrypted) {
        // 校验
        if (query.signature !== getSignature(timestamp, nonce, token)) {
          this.error = new Error('WeChat Invalid signature');
        }
      }

      // 取原始数据
      const buffer = yield getRawBody(this.req, {
        length: this.length,
        limit: '10mb',
        encoding: this.charset
      });
      const xml = buffer.toString('utf-8');

      // 将微信的原始数据放进 this.raw 中
      if (!this.raw) {
        this.raw = {};
      }
      this.raw.weixin = xml;

      // 解析 XML
      const parsed = yield parseXML(xml);
      // 格式化数据
      formated = formatMessage(parsed.xml);

      // 如果有加密，还要解密呢
      if (isEncrypted) {
        let encryptMessage = formated.Encrypt;
        if (query.msg_signature !== cryptor.getSignature(timestamp, nonce, encryptMessage)) {
          this.error = new Error('WeChat Invalid signature');
        }
        let decryptedXML = cryptor.decrypt(encryptMessage);
        let messageWrapXml = decryptedXML.message;
        if (messageWrapXml === '') {
          this.error = new Error('WeChat Invalid signature');
        } else {
          let decodedXML = parseXML(messageWrapXml);
          formated = formatMessage(decodedXML.xml);
        }
      }

      // 挂载处理后的微信消息
      this.weixin = formated;
      isWeixin = !!this.weixin;

      // TODO
      // 取session数据
      // if (this.sessionStore) {
      //   this.wxSessionId = formated.FromUserName;
      //   this.wxsession = yield this.sessionStore.get(this.wxSessionId);
      //   if (!this.wxsession) {
      //     this.wxsession = {};
      //     this.wxsession.cookie = this.session.cookie;
      //   }
      // }
    }

    // 业务逻辑处理
    yield next;


    // 识别类型为自定义的 application/weixin 的话，就对内容进行编码
    if (isWeixin) {
      // 处理 GET 请求
      if (method === 'GET') {
        if (isEncrypted) {
          let decrypted = cryptor.decrypt(echostr);
          // TODO 检查appId的正确性
          this.body = decrypted.message;
        } else {
          // 直接返回
          this.body = echostr;
        }

        // 返回文本
        this.type = 'text/plain';

        // 处理 POST 请求
      } else if (method === 'POST') {
        // TODO
        // 更新session
        // if (this.sessionStore) {
        //   if (!this.wxsession) {
        //     if (this.wxSessionId) {
        //       yield this.sessionStore.destroy(this.wxSessionId);
        //     }
        //   } else {
        //     yield this.sessionStore.set(this.wxSessionId, this.wxsession);
        //   }
        // }

        let replyXML = reply(this.body, formated.ToUserName, formated.FromUserName);

        if (!query.encrypt_type || query.encrypt_type === 'raw') {
          this.body = replyXML;
        } else {
          let wrap = {};
          wrap.encrypt = cryptor.encrypt(replyXML);
          wrap.nonce = parseInt((Math.random() * 100000000000), 10);
          wrap.timestamp = Date.now();
          wrap.signature = cryptor.getSignature(wrap.timestamp, wrap.nonce, wrap.encrypt);
          this.body = tpl.encryptWrap(wrap);
        }

        // 返回 XML
        this.type = 'application/xml';
      }
    }
  };
};`

**Comment by JacksonTian** [comment]
你应该调整路由，心跳检测的路由和微信处理的路由不应该混在一起。
